# Generated by Django 4.2.3 on 2023-07-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="contacts",
                        to="my_app.contacts",
                    ),
                ),
            ],
        ),
    ]
