# Generated by Django 4.2.3 on 2023-07-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_groupcontacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(max_length=14),
        ),
    ]
